language: swift
osx_image: xcode8.3
xcode_workspace: Example/AXPhotoViewerExample.xcworkspace
xcode_scheme: AXPhotoViewerExample

before_install: pod repo update master --silent && pod install --project-directory=Example
script: xcodebuild -workspace Example/AXPhotoViewerExample.xcworkspace -scheme AXPhotoViewerExample build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO PROVISIONING_PROFILE="" | xcpretty && exit ${PIPESTATUS[0]}

